### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by eclarke12** [javieros105/FVTT-TokenHUDWildcard#1]
Hi! 

Can't wait to use this module, but I have a couple of small suggestions:
1. 	`let actor = game.actors.get(token.actorId);`
Could be `let actor = token.actor;`

2.	`let openButton = document.createElement("div");`
Instead of creating the div in the document root, why not create in the existing jquery html object from the hook?

3. You have some `console.log` statements scattered around the place -- if these were for debugging they should be cleaned up

Thanks for your time!

**Comment by javieros105** [comment]
Hey, thank you for the feedback.

I'm going to check the first point, because I think there was a reason why I did that, but maybe it was with the previous version, so I have to check it out.

With the second point, to be honest I've been working with javascript for a while already, maybe a year I think, but haven't had the chance to work with jquery so that didn't even occur to me, gonna make that change.

And yeah I forgot to check for the console.logs, going to clean those up in a bit and make a patch version.

I'll be making those other changes probably during the weekend.

I'm glad some people are having interest in this :D

**Comment by javieros105** [comment]
So, made some big changes. Cleaned up the console.logs and refactored the code to fix some functionalities.

The first point tho I can't change because the renderTokenHUD hook returns a token without the actor information, only the token data itself and the actorId is the best thing to get the actual actor.

I'm going to close it for now but if any other things springs up I can look into it
