### ISSUE TITLE
[Feature Request] Image/Size Match

### ISSUE THREAD

**Issue by brunocalado** [javieros105/FVTT-TokenHUDWildcard#19]
Hi.

You module is great!

Can you a way to change the size of the token when you change the image?
![image](https://user-images.githubusercontent.com/4999783/123978718-79fede00-d996-11eb-9750-16237ad8b46c.png)

Sugestion
- Let the user add to the image name a code:
great_eagle_size3.jpg
size(?) will change the size of the target 
![image](https://user-images.githubusercontent.com/4999783/123978985-b03c5d80-d996-11eb-8a31-2b0d297819e3.png)

**Comment by javieros105** [comment]
ohhhh that sounds lie a pretty awesome way of changing the size on the grid. I'm gonna see hw to implement it and use some kind of format to follow.

**Comment by jacksands** [comment]
perhaps a clickable options with 1/2x 1x 2x 3x default, or even a slider above or below the images for selection

**Comment by javieros105** [comment]
I was actually thinking that it could be even better, by using the image name, for example i have the names
Character_v1_width<number>_height<number>_scale<number>.png
Character_v2_width<number>_height<number>_scale<number>.png

And if parsing the string I find those values I can set the width height and scale automatically for that specific image.

**Comment by jacksands** [comment]
That would be awesome to define a default size indeed, but if there was an "on the fly" selection together with the image selector that would make possible to make a multiplier of the default, or 1x1 multiple if none... with that we could make a giant butterfly for example with 2 clicks... if you want. 

to note, both me and Bruno use your module on a werewolf game, and we love it, we can change the image forms anytime... I know people that use it on isometric, Gundam, etc... it is amazing... I just give the idea because it would help me a lot...

but thanks for the awesome module, we love it!!!

**Comment by javieros105** [comment]
that's awesome, really glad you guys like it. That could also be an option, adding buttons to the panel with size presets in case you wanna use those. But I think the data being in the image name gives a lot of flexibility so I'm gonna try to implement that  first then maybe add the option of buttons

**Comment by javieros105** [comment]
Just an update, been doing some tests and it's kinda working, want to clean it up a bit and maybe by the end of the week I can have an auto set height width and scale from the name of the image. Still pondering about adding bottons to the hud.

**Comment by jacksands** [comment]
Amazing!  thank you for your effort!
Anyway you choose will be fine, because even with some of my folders having dozens of images (normally for generic citizens or gards, etc) renaming them will be easy, especially with renamer software...

The hud buttons would be good for me for creating different monsters, using size changing spells, etc, but it also can be done with macros, that I already use, so it is just a detail.

Many of my maps are fully populated with different images thanks to your incredible module, so just for you to take the time and facing this Code black magic that I really don't understand at all is really appreciated!!

thank you!

**Comment by javieros105** [comment]
Just missing a part in the code where if there is no height width or scale in the filename it will use the corresponding value of the prototype token. Once I have that part finished, the update will go live

**Comment by jacksands** [comment]
ow, sorry for the late response... very happy about that!!
once again thanks for the effort

**Comment by javieros105** [comment]
Latest release adds the functionality to set dimensions through the wildcard image. Readme has instructions but I will put them here too to give them visibility 

- wildcard images use this pattern `name*`
- `name_height<number>_width<number>_scale<number>_.extension`, it's important that each parameter s preceded and followed by an underscore, so if you want to set up height, there has to be a `_height<number>_` somewhere in the name
- you can choose to change `<number>` for a positive integer or floating number and which one to fill. If there are any parameter missing then the module will use the prototype token parameters to fill the ones missing, so you can use images with no parameter setting at all or just set one or two of the parameters.
- these are valid filenames that will be picked up by the module `name.extension`, `name-different.extension`, `name-other_height2_scale1.5_.extension`
