### ISSUE TITLE
Not compatible with Foundry VTT versions newer than 0.6.5

### ISSUE THREAD

**Issue by jsan-tset** [javieros105/FVTT-TokenHUDWildcard#3]
When trying to use the last updated version it says "may not be compatible with versions newer than 0.6.5" (the actual Foundry version is 0.6.6).
Any idea to solve it?

(Sorry, i missclicked)

**Comment by javieros105** [comment]
Hey sorry about not responding earlier, been having some rough weeks and couldn't check this. It just says that because I hadn't had the opportunity to check on newer versions and update the package, it has now been checked for 0.6.6. It should work on 0.7.x because none of the changes in that release break the functioning of the module, but I haven't tested it yet.
